In [138]:
import pandas as pd
import numpy as np

In [188]:
def answer_one():
    energy = pd.read_excel("Energy Indicators (2).xls", skiprows=17, skipfooter=38)

    energy.columns = ["Delete 1", "Delete 2", "Country", "Energy Supply",
                      "Energy Supply per Capita", "% Renewable"]

    energy = energy.drop(['Delete 1', 'Delete 2'], axis=1)

    energy["Energy Supply"] = 1000000 * energy["Energy Supply"]

    energy = energy.replace(to_replace='\.+', value=np.NaN, regex=True)

    energy["Country"] = energy["Country"].replace(to_replace='Republic of Korea', 
                                                  value='South Korea', regex=True)
    energy["Country"] = energy["Country"].replace(to_replace='United States of America', 
                                                  value='United States', regex=True)
    energy["Country"] = energy["Country"].replace(to_replace='United Kingdom of Great Britain and Northern Ireland', 
                                                  value='United Kingdom', regex=True)
    energy["Country"] = energy["Country"].replace(to_replace='China, Hong Kong Special Administrative Region', 
                                                  value='Hong Kong', regex=True)

    energy = energy.replace(to_replace='[0-9]', value='', regex=True)
    energy = energy.replace(to_replace='\(.*\)', value='', regex=True)
    energy = energy.replace(to_replace='\s$', value='', regex=True)

    energy[energy['Country'] == 'Iran']

    ##########################################################################################

    gdp = pd.read_csv("gdp.csv", skiprows=4)
    #gdp['Country Name'] = 4

    gdp_replace_dict = {
        'Korea, Rep.': 'South Korea',
        'Iran, Islamic Rep.': 'Iran',
        'Hong Kong SAR, China': 'Hong Kong'
    }

    gdp['Country Name'] = gdp['Country Name'].replace(to_replace=gdp_replace_dict, regex=True)
    gdp = gdp.sort_values(by='Country Name')#.reset_index()
    gdp.sort_values(by='Country Name')[60:120]
    gdp[gdp['Country Name'] == 'United Kingdom']

    scim_en = pd.read_excel("scimagojr country rank 1996-2021 (1).xlsx")

    ############################################################################################

    energy_gdp = pd.merge(left=energy, right=gdp, left_on='Country', 
                          right_on='Country Name', how='inner')

    join_df = pd.merge(left=energy_gdp, right=scim_en, left_on='Country', 
                       right_on='Country', how='inner')

    join_df = join_df.set_index('Country')

    join_df = join_df[['Rank', 'Documents', 'Citable documents', 'Citations', 
                       'Self-citations', 'Citations per document', 'H index', 
                       'Energy Supply', 'Energy Supply per Capita', '% Renewable', 
                       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]

    join_df = join_df.sort_values(by='Rank').head(15)

    return join_df

answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,303064,301778,3036531,2092737,10.02,273,1.271910e+11,93.0,19.754910,2.752132e+12,3.550343e+12,4.594307e+12,5.101703e+12,6.087164e+12,7.551500e+12,8.532230e+12,9.570406e+12,1.047568e+13,1.106155e+13
United States,2,184851,181106,2623922,819242,14.19,389,9.083800e+10,286.0,11.570980,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
India,3,60257,58589,590570,213760,9.80,198,3.319500e+10,26.0,14.969080,9.402599e+11,1.216735e+12,1.198896e+12,1.341887e+12,1.675615e+12,1.823050e+12,1.827638e+12,1.856722e+12,2.039127e+12,2.103588e+12
Japan,4,52780,52281,557023,132113,10.55,203,1.898400e+10,149.0,10.232820,4.601663e+12,4.579751e+12,5.106679e+12,5.289493e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
United Kingdom,5,47141,45928,748994,132737,15.89,244,7.920000e+09,124.0,10.600470,2.717060e+12,3.106182e+12,2.938882e+12,2.425798e+12,2.491110e+12,2.674891e+12,2.719158e+12,2.803291e+12,3.087166e+12,2.956574e+12
Germany,6,42343,41464,528645,115432,12.48,211,1.326100e+10,165.0,17.901530,2.994704e+12,3.425578e+12,3.745264e+12,3.411261e+12,3.399668e+12,3.749315e+12,3.527143e+12,3.733805e+12,3.889093e+12,3.357586e+12
Russian Federation,7,39424,39189,142937,67935,3.63,96,3.070900e+10,214.0,17.288680,9.899305e+11,1.299706e+12,1.660846e+12,1.222644e+12,1.524917e+12,2.045926e+12,2.208296e+12,2.292473e+12,2.059242e+12,1.363481e+12
Canada,8,35588,34940,665415,113363,18.70,246,1.043100e+10,296.0,61.945430,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,31260,29959,433388,105641,13.86,177,6.530000e+09,109.0,33.667230,1.949552e+12,2.213102e+12,2.408655e+12,2.199929e+12,2.136100e+12,2.294994e+12,2.086958e+12,2.141924e+12,2.162010e+12,1.836638e+12
South Korea,10,31200,30949,405923,74753,13.01,169,1.100700e+10,221.0,2.279353,1.053217e+12,1.172614e+12,1.047339e+12,9.439419e+11,1.144067e+12,1.253223e+12,1.278428e+12,1.370795e+12,1.484318e+12,1.465773e+12
France,11,26848,26320,403834,73792,15.04,190,1.059700e+10,166.0,17.020280,2.320536e+12,2.660591e+12,2.930304e+12,2.700887e+12,2.645188e+12,2.865158e+12,2.683672e+12,2.811877e+12,2.855964e+12,2.439189e+12
Iran,12,25481,25204,398571,122647,15.64,159,9.172000e+09,119.0,5.707721,2.662989e+11,3.498816e+11,4.123362e+11,4.163970e+11,4.868076e+11,6.261331e+11,6.440355e+11,4.927756e+11,4.603828e+11,4.082129e+11
Spain,13,24969,24505,427391,77583,17.12,187,4.923000e+09,106.0,37.968590,1.260399e+12,1.474003e+12,1.631863e+12,1.491473e+12,1.422108e+12,1.480710e+12,1.324744e+12,1.355143e+12,1.371223e+12,1.195600e+12
Brazil,14,23110,22762,219895,53635,9.52,139,1.214900e+10,59.0,69.648030,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12
Australia,15,22803,22276,396186,62694,17.37,192,5.386000e+09,231.0,11.810810,7.475562e+11,8.539554e+11,1.055127e+12,9.280430e+11,1.147589e+12,1.397908e+12,1.546509e+12,1.576335e+12,1.467505e+12,1.350534e+12

In [208]:
# What is the average GDP over the last 10 years for each country? 
# (exclude missing values from this calculation.)

# This function should return a Series named avgGDP with 15 countries 
# and their average GDP sorted in descending order.

def answer_two():
    top = answer_one()
    #df['sum'] = df[['2019', '2021']].apply(np.mean, axis=1)
    top['avg_gdp'] = top[['2006', '2007', '2008', '2009', '2010',
                          '2011', '2012', '2013', '2014', '2015']].apply(np.mean, axis=1)
    
    return top['avg_gdp'].sort_values(ascending=False)

print(answer_two())

Country
United States         1.570403e+13
China                 6.927702e+12
Japan                 5.239642e+12
Germany               3.523342e+12
United Kingdom        2.792011e+12
France                2.691337e+12
Italy                 2.142986e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.400727e+12
South Korea           1.221372e+12
Australia             1.207106e+12
Iran                  4.563261e+11
Name: avg_gdp, dtype: float64

In [217]:
# By how much had the GDP changed over the 10 year span 
# for the country with the 6th largest average GDP?

#This function should return a single number.

def answer_three():
    top_df = answer_one()
    avg_gdp = answer_two()
    sixth_gdp_country = avg_gdp.index[5]
    #df.loc['Ukraine', '2021'] - df.loc['Ukraine', '2019']
    gdp_diff = top_df.loc[sixth_gdp_country, '2015'] - top_df.loc[sixth_gdp_country, '2006']
    return gdp_diff

print(answer_three())

118652421857.7998

In [235]:
def answer_four():
    #df['ratio'] = df['2021'] / df['2019']
    top_df = answer_one()
    top_df['citations_ratio'] = top_df['Self-citations'] / top_df['Citations']
    citations_sorted_sr = top_df['citations_ratio'].sort_values(ascending=False)

    max_value = citations_sorted_sr.iloc[0]
    max_country = citations_sorted_sr.index[0]
 
    return (max_country, max_value)

print(answer_four())

('China', 0.689186772669207)

In [240]:
def answer_five():
    top_df = answer_one()
    top_df['population'] = top_df['Energy Supply'] / top_df['Energy Supply per Capita']
    populations_sorted_desc_sr = top_df['population'].sort_values(ascending=False)
    third_populous_country = populations_sorted_desc_sr.index[2]
    return third_populous_country

print(answer_five())

United States

In [246]:
def answer_six():
    top_df = answer_one()
    top_df['population'] = top_df['Energy Supply'] / top_df['Energy Supply per Capita']
    top_df['cit_docs_per_capita'] =  top_df['Citable documents'] / top_df['population']
    
    to_corr_df = top_df[['cit_docs_per_capita', 'Energy Supply per Capita']]
    coef_corr = to_corr_df.corr().iloc[0,1]
    return coef_corr
    
print(answer_six())

0.7272331912434824

In [282]:
def answer_seven():
    top_df = answer_one()
    top_df['population'] = top_df['Energy Supply'] / top_df['Energy Supply per Capita']
    continent_dict = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    df= pd.Series(data=continent_dict, name='continent').to_frame()
    top_df = pd.merge(left=top_df, right=df, left_index=True, 
                          right_index=True, how='inner')
    
    top_df_pop_cont = top_df[['population', 'continent']]
    
    #final_df = top_df_pop_cont.groupby('continent').apply(sum)
    final_df = top_df_pop_cont.groupby('continent').agg(['count', 'sum', 'mean', 'std'])
    return final_df
print(answer_seven())

              population
                   count           sum          mean           std
continent
Asia                   5  2.898666e+09  5.797333e+08  6.790979e+08
Australia              1  2.331602e+07  2.331602e+07           NaN
Europe                 6  4.579297e+08  7.632161e+07  3.464767e+07
North America          2  3.528552e+08  1.764276e+08  1.996696e+08
South America          1  2.059153e+08  2.059153e+08           NaN